-- ============================================================
-- 092: Partner-Repräsentanten & Dokumente
-- ============================================================

CREATE TABLE IF NOT EXISTS partner_representatives (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  type          ENUM('country','bundesland') NOT NULL DEFAULT 'country',
  code          VARCHAR(10)  NOT NULL COMMENT 'ISO 3166-1 alpha-2 oder DE-BW etc.',
  name_de       VARCHAR(100) NOT NULL,
  name_en       VARCHAR(100) NOT NULL,
  status        ENUM('free','occupied','pending') NOT NULL DEFAULT 'free',
  rep_name      VARCHAR(150) NULL COMMENT 'Name des Repräsentanten',
  rep_email     VARCHAR(150) NULL,
  rep_website   VARCHAR(255) NULL,
  flag_emoji    VARCHAR(10)  NULL,
  notes         TEXT         NULL,
  sort_order    INT          NOT NULL DEFAULT 0,
  created_at    DATETIME     NOT NULL DEFAULT NOW(),
  updated_at    DATETIME     NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  UNIQUE KEY uq_partner_code_type (code, type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partner_documents (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name_de       VARCHAR(200) NOT NULL,
  name_en       VARCHAR(200) NOT NULL,
  description_de TEXT        NULL,
  description_en TEXT        NULL,
  filename      VARCHAR(255) NOT NULL,
  file_path     VARCHAR(500) NOT NULL,
  file_size     INT          NULL,
  mime_type     VARCHAR(100) NULL,
  category      ENUM('info','contract','application','other') NOT NULL DEFAULT 'info',
  is_public     TINYINT(1)   NOT NULL DEFAULT 1,
  sort_order    INT          NOT NULL DEFAULT 0,
  created_at    DATETIME     NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed: wichtige Länder vorausfüllen
INSERT IGNORE INTO partner_representatives (type, code, name_de, name_en, flag_emoji, status, sort_order) VALUES
('country','DE','Deutschland','Germany','🇩🇪','occupied',1),
('country','AT','Österreich','Austria','🇦🇹','free',2),
('country','CH','Schweiz','Switzerland','🇨🇭','free',3),
('country','IT','Italien','Italy','🇮🇹','free',4),
('country','FR','Frankreich','France','🇫🇷','free',5),
('country','ES','Spanien','Spain','🇪🇸','free',6),
('country','PT','Portugal','Portugal','🇵🇹','free',7),
('country','NL','Niederlande','Netherlands','🇳🇱','free',8),
('country','BE','Belgien','Belgium','🇧🇪','free',9),
('country','PL','Polen','Poland','🇵🇱','free',10),
('country','CZ','Tschechien','Czech Republic','🇨🇿','free',11),
('country','SK','Slowakei','Slovakia','🇸🇰','free',12),
('country','HU','Ungarn','Hungary','🇭🇺','free',13),
('country','HR','Kroatien','Croatia','🇭🇷','free',14),
('country','RO','Rumänien','Romania','🇷🇴','free',15),
('country','BG','Bulgarien','Bulgaria','🇧🇬','free',16),
('country','GR','Griechenland','Greece','🇬🇷','free',17),
('country','TR','Türkei','Turkey','🇹🇷','free',18),
('country','UA','Ukraine','Ukraine','🇺🇦','free',19),
('country','GB','Großbritannien','United Kingdom','🇬🇧','free',20),
('country','IE','Irland','Ireland','🇮🇪','free',21),
('country','DK','Dänemark','Denmark','🇩🇰','free',22),
('country','SE','Schweden','Sweden','🇸🇪','free',23),
('country','NO','Norwegen','Norway','🇳🇴','free',24),
('country','FI','Finnland','Finland','🇫🇮','free',25),
('country','US','USA','USA','🇺🇸','free',30),
('country','CA','Kanada','Canada','🇨🇦','free',31),
('country','MX','Mexiko','Mexico','🇲🇽','free',32),
('country','BR','Brasilien','Brazil','🇧🇷','free',33),
('country','AR','Argentinien','Argentina','🇦🇷','free',34),
('country','AU','Australien','Australia','🇦🇺','free',40),
('country','NZ','Neuseeland','New Zealand','🇳🇿','free',41),
('country','JP','Japan','Japan','🇯🇵','free',50),
('country','KR','Südkorea','South Korea','🇰🇷','free',51),
('country','CN','China','China','🇨🇳','free',52),
('country','IN','Indien','India','🇮🇳','free',53),
('country','ZA','Südafrika','South Africa','🇿🇦','free',60),
-- Deutsche Bundesländer
('bundesland','DE-BW','Baden-Württemberg','Baden-Württemberg','','free',101),
('bundesland','DE-BY','Bayern','Bavaria','','free',102),
('bundesland','DE-BE','Berlin','Berlin','','free',103),
('bundesland','DE-BB','Brandenburg','Brandenburg','','free',104),
('bundesland','DE-HB','Bremen','Bremen','','free',105),
('bundesland','DE-HH','Hamburg','Hamburg','','free',106),
('bundesland','DE-HE','Hessen','Hesse','','free',107),
('bundesland','DE-MV','Mecklenburg-Vorpommern','Mecklenburg-Vorpommern','','free',108),
('bundesland','DE-NI','Niedersachsen','Lower Saxony','','free',109),
('bundesland','DE-NW','Nordrhein-Westfalen','North Rhine-Westphalia','','free',110),
('bundesland','DE-RP','Rheinland-Pfalz','Rhineland-Palatinate','','free',111),
('bundesland','DE-SL','Saarland','Saarland','','free',112),
('bundesland','DE-SN','Sachsen','Saxony','','free',113),
('bundesland','DE-ST','Sachsen-Anhalt','Saxony-Anhalt','','free',114),
('bundesland','DE-SH','Schleswig-Holstein','Schleswig-Holstein','','free',115),
('bundesland','DE-TH','Thüringen','Thuringia','','free',116);
