-- ============================================================
-- 093: US-Bundesstaaten für Partner-Repräsentanten
-- ============================================================

ALTER TABLE partner_representatives
  MODIFY type ENUM('country','bundesland','us_state') NOT NULL DEFAULT 'country';

INSERT IGNORE INTO partner_representatives (type, code, name_de, name_en, flag_emoji, status, sort_order) VALUES
('us_state','US-AL','Alabama','Alabama','',         'free',201),
('us_state','US-AK','Alaska','Alaska','',           'free',202),
('us_state','US-AZ','Arizona','Arizona','',         'free',203),
('us_state','US-AR','Arkansas','Arkansas','',       'free',204),
('us_state','US-CA','Kalifornien','California','',  'free',205),
('us_state','US-CO','Colorado','Colorado','',       'free',206),
('us_state','US-CT','Connecticut','Connecticut','', 'free',207),
('us_state','US-DE','Delaware','Delaware','',       'free',208),
('us_state','US-FL','Florida','Florida','',         'free',209),
('us_state','US-GA','Georgia','Georgia','',         'free',210),
('us_state','US-HI','Hawaii','Hawaii','',           'free',211),
('us_state','US-ID','Idaho','Idaho','',             'free',212),
('us_state','US-IL','Illinois','Illinois','',       'free',213),
('us_state','US-IN','Indiana','Indiana','',         'free',214),
('us_state','US-IA','Iowa','Iowa','',               'free',215),
('us_state','US-KS','Kansas','Kansas','',           'free',216),
('us_state','US-KY','Kentucky','Kentucky','',       'free',217),
('us_state','US-LA','Louisiana','Louisiana','',     'free',218),
('us_state','US-ME','Maine','Maine','',             'free',219),
('us_state','US-MD','Maryland','Maryland','',       'free',220),
('us_state','US-MA','Massachusetts','Massachusetts','','free',221),
('us_state','US-MI','Michigan','Michigan','',       'free',222),
('us_state','US-MN','Minnesota','Minnesota','',     'free',223),
('us_state','US-MS','Mississippi','Mississippi','', 'free',224),
('us_state','US-MO','Missouri','Missouri','',       'free',225),
('us_state','US-MT','Montana','Montana','',         'free',226),
('us_state','US-NE','Nebraska','Nebraska','',       'free',227),
('us_state','US-NV','Nevada','Nevada','',           'free',228),
('us_state','US-NH','New Hampshire','New Hampshire','','free',229),
('us_state','US-NJ','New Jersey','New Jersey','',   'free',230),
('us_state','US-NM','New Mexico','New Mexico','',   'free',231),
('us_state','US-NY','New York','New York','',       'free',232),
('us_state','US-NC','North Carolina','North Carolina','','free',233),
('us_state','US-ND','North Dakota','North Dakota','','free',234),
('us_state','US-OH','Ohio','Ohio','',               'free',235),
('us_state','US-OK','Oklahoma','Oklahoma','',       'free',236),
('us_state','US-OR','Oregon','Oregon','',           'free',237),
('us_state','US-PA','Pennsylvania','Pennsylvania','','free',238),
('us_state','US-RI','Rhode Island','Rhode Island','','free',239),
('us_state','US-SC','South Carolina','South Carolina','','free',240),
('us_state','US-SD','South Dakota','South Dakota','','free',241),
('us_state','US-TN','Tennessee','Tennessee','',     'free',242),
('us_state','US-TX','Texas','Texas','',             'free',243),
('us_state','US-UT','Utah','Utah','',               'free',244),
('us_state','US-VT','Vermont','Vermont','',         'free',245),
('us_state','US-VA','Virginia','Virginia','',       'free',246),
('us_state','US-WA','Washington','Washington','',   'free',247),
('us_state','US-WV','West Virginia','West Virginia','','free',248),
('us_state','US-WI','Wisconsin','Wisconsin','',     'free',249),
('us_state','US-WY','Wyoming','Wyoming','',         'free',250);

-- Weitere afrikanische Länder (Ghana bereits besetzt)
INSERT IGNORE INTO partner_representatives (type, code, name_de, name_en, flag_emoji, status, sort_order) VALUES
('country','GH','Ghana','Ghana','',              'occupied',61),
('country','NG','Nigeria','Nigeria','',           'free',62),
('country','KE','Kenia','Kenya','',               'free',63),
('country','ET','Äthiopien','Ethiopia','',        'free',64),
('country','TZ','Tansania','Tanzania','',         'free',65),
('country','UG','Uganda','Uganda','',             'free',66),
('country','SN','Senegal','Senegal','',           'free',67),
('country','CI','Elfenbeinküste','Ivory Coast','','free',68),
('country','CM','Kamerun','Cameroon','',          'free',69),
('country','MA','Marokko','Morocco','',           'free',70),
('country','DZ','Algerien','Algeria','',          'free',71),
('country','EG','Ägypten','Egypt','',             'free',72),
('country','TN','Tunesien','Tunisia','',          'free',73);
