-- ============================================================
-- 094: Alle Länder der Welt als "frei" vorbelegen
-- ============================================================

INSERT IGNORE INTO partner_representatives (type, code, name_de, name_en, flag_emoji, status, sort_order) VALUES
-- Europa (weitere)
('country','IS','Island','Iceland','',              'free',26),
('country','LU','Luxemburg','Luxembourg','',        'free',27),
('country','AL','Albanien','Albania','',            'free',28),
('country','RS','Serbien','Serbia','',              'free',29),
('country','BA','Bosnien-Herzegowina','Bosnia and Herz.','','free',29),
('country','ME','Montenegro','Montenegro','',       'free',29),
('country','MK','Nordmazedonien','North Macedonia','','free',29),
('country','SI','Slowenien','Slovenia','',          'free',29),
('country','MD','Moldau','Moldova','',              'free',29),
('country','BY','Weißrussland','Belarus','',        'free',29),
('country','LV','Lettland','Latvia','',             'free',29),
('country','LT','Litauen','Lithuania','',           'free',29),
('country','EE','Estland','Estonia','',             'free',29),
('country','CY','Zypern','Cyprus','',               'free',29),
('country','MT','Malta','Malta','',                 'free',29),
('country','GE','Georgien','Georgia','',            'free',29),
('country','AM','Armenien','Armenia','',            'free',29),
('country','AZ','Aserbaidschan','Azerbaijan','',    'free',29),
('country','RU','Russland','Russia','',             'free',29),
-- Naher Osten / Zentralasien
('country','SA','Saudi-Arabien','Saudi Arabia','',  'free',80),
('country','AE','Vereinigte Arab. Emirate','United Arab Emirates','','free',81),
('country','IL','Israel','Israel','',               'free',82),
('country','JO','Jordanien','Jordan','',            'free',83),
('country','LB','Libanon','Lebanon','',             'free',84),
('country','SY','Syrien','Syria','',                'free',85),
('country','IQ','Irak','Iraq','',                   'free',86),
('country','IR','Iran','Iran','',                   'free',87),
('country','KW','Kuwait','Kuwait','',               'free',88),
('country','QA','Katar','Qatar','',                 'free',89),
('country','YE','Jemen','Yemen','',                 'free',90),
('country','OM','Oman','Oman','',                   'free',91),
('country','PS','Palästina','Palestine','',         'free',92),
('country','KZ','Kasachstan','Kazakhstan','',       'free',93),
('country','UZ','Usbekistan','Uzbekistan','',       'free',94),
('country','TM','Turkmenistan','Turkmenistan','',   'free',95),
('country','TJ','Tadschikistan','Tajikistan','',    'free',96),
('country','KG','Kirgisistan','Kyrgyzstan','',      'free',97),
('country','AF','Afghanistan','Afghanistan','',     'free',98),
-- Asien (weitere)
('country','PK','Pakistan','Pakistan','',           'free',54),
('country','BD','Bangladesch','Bangladesh','',      'free',55),
('country','LK','Sri Lanka','Sri Lanka','',         'free',56),
('country','NP','Nepal','Nepal','',                 'free',57),
('country','BT','Bhutan','Bhutan','',               'free',58),
('country','MM','Myanmar','Myanmar','',             'free',59),
('country','TH','Thailand','Thailand','',           'free',60),
('country','VN','Vietnam','Vietnam','',             'free',60),
('country','KH','Kambodscha','Cambodia','',         'free',60),
('country','LA','Laos','Laos','',                   'free',60),
('country','MY','Malaysia','Malaysia','',           'free',60),
('country','ID','Indonesien','Indonesia','',        'free',60),
('country','PH','Philippinen','Philippines','',     'free',60),
('country','MN','Mongolei','Mongolia','',           'free',60),
('country','TW','Taiwan','Taiwan','',               'free',60),
('country','KP','Nordkorea','North Korea','',       'free',60),
-- Ozeanien (weitere)
('country','PG','Papua-Neuguinea','Papua New Guinea','','free',42),
('country','FJ','Fidschi','Fiji','',                'free',43),
('country','SB','Salomonen','Solomon Islands','',   'free',44),
('country','VU','Vanuatu','Vanuatu','',             'free',45),
-- Amerika (weitere)
('country','CL','Chile','Chile','',                 'free',35),
('country','CO','Kolumbien','Colombia','',          'free',36),
('country','VE','Venezuela','Venezuela','',         'free',37),
('country','PE','Peru','Peru','',                   'free',38),
('country','EC','Ecuador','Ecuador','',             'free',39),
('country','BO','Bolivien','Bolivia','',            'free',40),
('country','PY','Paraguay','Paraguay','',           'free',40),
('country','UY','Uruguay','Uruguay','',             'free',40),
('country','GY','Guyana','Guyana','',               'free',40),
('country','SR','Suriname','Suriname','',           'free',40),
('country','GT','Guatemala','Guatemala','',         'free',40),
('country','HN','Honduras','Honduras','',           'free',40),
('country','SV','El Salvador','El Salvador','',     'free',40),
('country','NI','Nicaragua','Nicaragua','',         'free',40),
('country','CR','Costa Rica','Costa Rica','',       'free',40),
('country','PA','Panama','Panama','',               'free',40),
('country','CU','Kuba','Cuba','',                   'free',40),
('country','DO','Dominikanische Republik','Dominican Rep.','','free',40),
('country','HT','Haiti','Haiti','',                 'free',40),
('country','JM','Jamaika','Jamaica','',             'free',40),
('country','TT','Trinidad und Tobago','Trinidad and Tobago','','free',40),
('country','BZ','Belize','Belize','',               'free',40),
-- Afrika (weitere)
('country','LY','Libyen','Libya','',                'free',73),
('country','SD','Sudan','Sudan','',                 'free',74),
('country','SS','Südsudan','S. Sudan','',           'free',75),
('country','SO','Somalia','Somalia','',             'free',76),
('country','MW','Malawi','Malawi','',               'free',77),
('country','ZM','Sambia','Zambia','',               'free',78),
('country','ZW','Simbabwe','Zimbabwe','',           'free',79),
('country','MZ','Mosambik','Mozambique','',         'free',79),
('country','NA','Namibia','Namibia','',             'free',79),
('country','BW','Botswana','Botswana','',           'free',79),
('country','SZ','Eswatini','eSwatini','',           'free',79),
('country','LS','Lesotho','Lesotho','',             'free',79),
('country','AO','Angola','Angola','',               'free',79),
('country','CD','Dem. Rep. Kongo','Dem. Rep. Congo','','free',79),
('country','CG','Kongo','Congo','',                 'free',79),
('country','CF','Zentralafrikanische Rep.','Central African Rep.','','free',79),
('country','RW','Ruanda','Rwanda','',               'free',79),
('country','BI','Burundi','Burundi','',             'free',79),
('country','TD','Tschad','Chad','',                 'free',79),
('country','NE','Niger','Niger','',                 'free',79),
('country','ML','Mali','Mali','',                   'free',79),
('country','BF','Burkina Faso','Burkina Faso','',   'free',79),
('country','GN','Guinea','Guinea','',               'free',79),
('country','GW','Guinea-Bissau','Guinea-Bissau','', 'free',79),
('country','SL','Sierra Leone','Sierra Leone','',   'free',79),
('country','LR','Liberia','Liberia','',             'free',79),
('country','GA','Gabun','Gabon','',                 'free',79),
('country','GQ','Äquatorialguinea','Eq. Guinea','', 'free',79),
('country','MR','Mauretanien','Mauritania','',      'free',79),
('country','MG','Madagaskar','Madagascar','',       'free',79),
('country','GM','Gambia','Gambia','',               'free',79),
('country','DJ','Dschibuti','Djibouti','',          'free',79),
('country','ER','Eritrea','Eritrea','',             'free',79),
('country','BJ','Benin','Benin','',                 'free',79),
('country','TG','Togo','Togo','',                   'free',79);
